# Generated by Django 5.2.7 on 2025-11-02 00:53

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_id', models.CharField(db_index=True, help_text='The unique session or context ID from the A2A protocol.', max_length=255)),
                ('user_message', models.TextField(help_text='The message sent by the user.')),
                ('agent_message', models.TextField(help_text='The response generated by the agent.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the interaction.')),
            ],
            options={
                'verbose_name': 'Conversation History',
                'verbose_name_plural': 'Conversation Histories',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for each piece of content.', primary_key=True, serialize=False)),
                ('source_url', models.URLField(help_text='The original URL of the content to prevent duplicates.', max_length=1000, unique=True)),
                ('title', models.CharField(help_text='The original or AI-generated title of the content.', max_length=255)),
                ('processed_text', models.TextField(help_text='The AI-cleaned, summarized, and formatted content.')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, help_text='Vector embedding of the processed text for semantic search.')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('news', 'News')], db_index=True, help_text='Categorizes the content as educational (article) or timely (news).', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='The original publication date of the news or article, if available.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the content was first added to our database.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the content was last updated.')),
            ],
            options={
                'verbose_name': 'Processed Content',
                'verbose_name_plural': 'Processed Contents',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
