# Generated by Django 5.2.7 on 2025-11-07 15:10

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('raw_content', models.TextField()),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('news', 'News')], max_length=20)),
                ('published_at_str', models.CharField(blank=True, max_length=100, null=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Raw Content',
                'verbose_name_plural': 'Raw Contents',
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameField(
            model_name='processedcontent',
            old_name='processed_text',
            new_name='processed_content',
        ),
        migrations.AlterField(
            model_name='processedcontent',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, help_text='Vector embedding of the processed text for semantic search.'),
        ),
    ]
