# Generated by Django 5.2.7 on 2025-11-07 21:11

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex_agent', '0003_alter_processedcontent_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedcontent',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, help_text='Vector embedding of the processed text for semantic search.'),
        ),
    ]
