# Generated by Django 5.2.7 on 2025-11-08 02:53

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex_agent', '0004_alter_processedcontent_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedcontent',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, help_text='Vector embedding of the processed text for semantic search.'),
        ),
    ]
